# Generated by Django 5.1.2 on 2025-12-04 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.project'),
        ),
        migrations.AddField(
            model_name='boardlist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='boards.board'),
        ),
        migrations.AlterUniqueTogether(
            name='board',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='boardlist',
            unique_together={('board', 'name')},
        ),
    ]
